#version: '3.8'

services:
  # MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  # MySQL for Order Service
  mysql-order:
    image: mysql:8.0
    container_name: mysql-order
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: order_service
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-order-data:/var/lib/mysql

  # MySQL for Inventory Service
  mysql-inventory:
    image: mysql:8.0
    container_name: mysql-inventory
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: inventory_service
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-inventory-data:/var/lib/mysql

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: keycloak
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realms-export:/opt/keycloak/data/import

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka
  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  # Discovery Server
  discovery-server:
    image: asia-southeast1-docker.pkg.dev/${PROJECT_ID}/microservices-repo/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - zipkin

  # API Gateway
  api-gateway:
    image: asia-southeast1-docker.pkg.dev/${PROJECT_ID}/microservices-repo/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8181:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY: TRACE
    depends_on:
      - discovery-server
      - keycloak
      - zipkin

  # Product Service
  product-service:
    image: asia-southeast1-docker.pkg.dev/${PROJECT_ID}/microservices-repo/product-service:latest
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongo
      - discovery-server
      - api-gateway
      - zipkin

  # Order Service
  order-service:
    image: asia-southeast1-docker.pkg.dev/${PROJECT_ID}/microservices-repo/order-service:latest
    container_name: order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql-order
      - broker
      - discovery-server
      - api-gateway
      - zipkin

  # Inventory Service
  inventory-service:
    image: asia-southeast1-docker.pkg.dev/${PROJECT_ID}/microservices-repo/inventory-service:latest
    container_name: inventory-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql-inventory
      - discovery-server
      - api-gateway
      - zipkin

  # Notification Service
  notification-service:
    image: asia-southeast1-docker.pkg.dev/${PROJECT_ID}/microservices-repo/notification-service:latest
    container_name: notification-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - broker
      - discovery-server
      - api-gateway
      - zipkin

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

  chatbot-service:
      build: ./services/chatbot-service
      container_name: chatbot-service
      environment:
        - GOOGLE_API_KEY=${GOOGLE_API_KEY}
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      ports:
        - "8095:8095"
      depends_on:
        - discovery-server

volumes:
  mongo-data:
  mysql-order-data:
  mysql-inventory-data:
  grafana-data:
