apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices

resources:
  # Infrastructure
  - k8s-mongo.yaml
  - k8s-mysql-order.yaml
  - k8s-mysql-inventory.yaml
  - k8s-keycloak.yaml

  # Services
  - k8s-discovery-server.yaml
  - k8s-product-service.yaml
  - k8s-order-service.yaml
  - k8s-inventory-service.yaml
  - k8s-notification-service.yaml
  - k8s-api-gateway.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd